name = "zori-pay"
compatibility_date = "2024-01-01"

pages_build_output_dir = "dist"

[env.production]
vars = { VITE_API_URL = "https://api.zoripay.xyz/v1" }

[env.preview]
vars = { VITE_API_URL = "https://api.zoripay.xyz/v1" }
